sudo: false

language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
- npm prune

script:
  - npm run build
  - npm test

after_success:
  - test $TRAVIS_EVENT_TYPE = "pull_request" && echo "Deploy PR to Now" && now-travis --env DATO_API_TOKEN --env RELOAD_TOKEN
  - test $TRAVIS_EVENT_TYPE = "push" && test $TRAVIS_BRANCH = "master" && echo "Deploy master and alias" && now-travis --env DATO_API_TOKEN --env RELOAD_TOKEN && now alias --token=$NOW_TOKEN
